"use server";
import { revalidatePath } from "next/cache";import { redirect } from "next/navigation";import { z } from "zod";
import { getMyPrimaryHousehold } from "@/features/household/api";import { getWallet } from "@/features/wallets/api";import { requireUser } from "@/lib/auth/require-user";import { logDatabaseErrorInDev } from "@/lib/supabase/log-error";import type { ActionState } from "@/lib/types/action-state";import { normalizeAmount,positiveAmountSchema } from "@/lib/validation/money";
import { createBill,payBill,setBillTags,skipBill,updateBill } from "./api";
const uuid=z.string().uuid();const optUuid=z.string().uuid().nullish().transform(v=>v||null);const opt=z.string().trim().max(200).nullish().transform(v=>v||null);const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);const tags=z.array(uuid).max(20);
const schema=z.object({id:uuid.optional(),scope:z.enum(["PERSONAL","HOUSEHOLD"]).nullish(),name:z.string().trim().min(1).max(60),amount:positiveAmountSchema,currency:z.string().trim().toUpperCase().regex(/^[A-Z]{3}$/),walletId:optUuid,pocketId:optUuid,categoryId:uuid,title:opt,note:opt,recurrenceType:z.enum(["ONE_TIME","WEEKLY","MONTHLY","YEARLY"]),intervalCount:z.coerce.number().int().min(1),startDate:date,endDate:date.nullish().transform(v=>v||null),tagIds:tags}).superRefine((v,c)=>{if(v.endDate&&v.endDate<v.startDate)c.addIssue({code:"custom",message:"วันสิ้นสุดไม่ถูกต้อง",path:["endDate"]});if(v.recurrenceType==="ONE_TIME"&&v.intervalCount!==1)c.addIssue({code:"custom",message:"บิลครั้งเดียวต้องมีช่วง 1",path:["intervalCount"]})});
function input(fd:FormData){return{ id:fd.get("id"),scope:fd.get("scope"),name:fd.get("name"),amount:fd.get("amount"),currency:fd.get("currency"),walletId:fd.get("walletId"),pocketId:fd.get("pocketId"),categoryId:fd.get("categoryId"),title:fd.get("title"),note:fd.get("note"),recurrenceType:fd.get("recurrenceType"),intervalCount:fd.get("intervalCount"),startDate:fd.get("startDate"),endDate:fd.get("endDate"),tagIds:fd.getAll("tagIds")}}
async function ownership(s:Awaited<ReturnType<typeof requireUser>>["supabase"],uid:string,v:{scope?:"PERSONAL"|"HOUSEHOLD"|null;walletId:string|null}){if(v.walletId){const w=await getWallet(s,v.walletId);if(!w)throw new Error("Wallet unavailable");return{scope:w.scope,owner_user_id:w.owner_user_id,household_id:w.household_id}}if(v.scope==="HOUSEHOLD"){const h=await getMyPrimaryHousehold(s,uid);if(!h)throw new Error("Household unavailable");return{scope:"HOUSEHOLD" as const,owner_user_id:null,household_id:h.id}}return{scope:"PERSONAL" as const,owner_user_id:uid,household_id:null}}
export async function createBillAction(_s:ActionState,fd:FormData):Promise<ActionState>{const {supabase,user}=await requireUser();const p=schema.safeParse(input(fd));if(!p.success)return{error:p.error.issues[0]?.message??"Invalid input"};let id:string;try{const own=await ownership(supabase,user.id,p.data);const row=await createBill(supabase,{...own,name:p.data.name,amount:normalizeAmount(p.data.amount),currency:p.data.currency,wallet_id:p.data.walletId,pocket_id:p.data.pocketId,category_id:p.data.categoryId,title:p.data.title,note:p.data.note,recurrence_type:p.data.recurrenceType,interval_count:p.data.intervalCount,start_date:p.data.startDate,end_date:p.data.endDate,created_by:user.id});id=row.id;await setBillTags(supabase,row.id,p.data.tagIds)}catch(e){logDatabaseErrorInDev("createBill failed",e);return{error:"สร้างบิลไม่สำเร็จ — ตรวจสอบขอบเขต สกุลเงิน และข้อมูลอ้างอิง"}}revalidatePath("/finance");revalidatePath("/finance/bills");redirect(`/finance/bills/${id}`)}
export async function updateBillAction(_s:ActionState,fd:FormData):Promise<ActionState>{const {supabase}=await requireUser();const p=schema.safeParse(input(fd));if(!p.success||!p.data.id)return{error:p.success?"Missing Bill":p.error.issues[0]?.message};try{await updateBill(supabase,p.data.id,{name:p.data.name,amount:normalizeAmount(p.data.amount),wallet_id:p.data.walletId,pocket_id:p.data.pocketId,category_id:p.data.categoryId,title:p.data.title,note:p.data.note,recurrence_type:p.data.recurrenceType,interval_count:p.data.intervalCount,start_date:p.data.startDate,end_date:p.data.endDate});await setBillTags(supabase,p.data.id,p.data.tagIds)}catch(e){logDatabaseErrorInDev("updateBill failed",e);return{error:"แก้ไขบิลไม่สำเร็จ"}}revalidatePath("/finance/bills");redirect(`/finance/bills/${p.data.id}`)}
async function life(fd:FormData,key:"paused_at"|"archived_at",value:string|null){const {supabase}=await requireUser();const id=uuid.parse(fd.get("id"));await updateBill(supabase,id,{[key]:value});revalidatePath("/finance/bills");revalidatePath(`/finance/bills/${id}`)}
export async function pauseBillAction(fd:FormData){await life(fd,"paused_at",new Date().toISOString())}export async function resumeBillAction(fd:FormData){await life(fd,"paused_at",null)}export async function archiveBillAction(fd:FormData){await life(fd,"archived_at",new Date().toISOString())}export async function restoreBillAction(fd:FormData){await life(fd,"archived_at",null)}
export async function skipBillAction(_s:ActionState,fd:FormData):Promise<ActionState>{const {supabase}=await requireUser();try{await skipBill(supabase,uuid.parse(fd.get("occurrenceId")))}catch(e){logDatabaseErrorInDev("skipBill failed",e);return{error:"ข้ามงวดไม่สำเร็จ"}}revalidatePath("/finance");revalidatePath("/finance/bills");return{}}
const paySchema=z.object({occurrenceId:uuid,walletId:uuid,pocketId:uuid,categoryId:uuid,amount:positiveAmountSchema,title:opt,note:opt,occurredAt:date,tagIds:tags});
export async function payBillAction(_s:ActionState,fd:FormData):Promise<ActionState>{const {supabase}=await requireUser();const p=paySchema.safeParse({occurrenceId:fd.get("occurrenceId"),walletId:fd.get("walletId"),pocketId:fd.get("pocketId"),categoryId:fd.get("categoryId"),amount:fd.get("amount"),title:fd.get("title"),note:fd.get("note"),occurredAt:fd.get("occurredAt"),tagIds:fd.getAll("tagIds")});if(!p.success)return{error:p.error.issues[0]?.message??"Invalid input"};try{await payBill(supabase,{...p.data,amount:normalizeAmount(p.data.amount),occurredAt:new Date(`${p.data.occurredAt}T12:00:00+07:00`).toISOString()})}catch(e){logDatabaseErrorInDev("payBill failed",e);return{error:"จ่ายบิลไม่สำเร็จ — อาจถูกจ่ายแล้วหรือข้อมูลชำระไม่ถูกต้อง"}}revalidatePath("/finance");revalidatePath("/finance/bills");redirect("/finance/bills")}
