import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import { logDatabaseErrorInDev } from "@/lib/supabase/log-error";
import { normalizeDatabaseMoney } from "@/lib/utils/money";
import type { Database } from "@/types/database";
import { billDisplayStatus } from "./domain";
import type { BillOccurrenceSummary,BillRecurrence,BillSummary } from "./types";

const BILL_SELECT="id,scope,owner_user_id,household_id,name,amount,currency,wallet_id,wallet:wallets(name,is_archived),pocket_id,pocket:pockets(name,is_archived),category_id,category:categories(name,archived_at),title,note,recurrence_type,interval_count,start_date,end_date,paused_at,archived_at";
type RawBill={id:string;scope:"PERSONAL"|"HOUSEHOLD";owner_user_id:string|null;household_id:string|null;name:string;amount:string|number;currency:string;wallet_id:string|null;wallet:{name:string;is_archived:boolean}|null;pocket_id:string|null;pocket:{name:string;is_archived:boolean}|null;category_id:string;category:{name:string;archived_at:string|null}|null;title:string|null;note:string|null;recurrence_type:BillRecurrence;interval_count:number;start_date:string;end_date:string|null;paused_at:string|null;archived_at:string|null};
type BillTag={bill_id:string;tag:{id:string;name:string;archived_at:string|null}|null};

async function tagsFor(s:SupabaseClient<Database>,ids:string[]){const out=new Map<string,Array<{id:string;name:string;archivedAt:string|null}>>();if(!ids.length)return out;const {data,error}=await s.from("bill_tags").select("bill_id,tag:tags(id,name,archived_at)").in("bill_id",ids);if(error){logDatabaseErrorInDev("bill tags read failed",error);return out}for(const row of (data??[]) as unknown as BillTag[]){if(!row.tag)continue;const a=out.get(row.bill_id)??[];a.push({id:row.tag.id,name:row.tag.name,archivedAt:row.tag.archived_at});out.set(row.bill_id,a)}return out}
function mapBill(r:RawBill,t:BillSummary["tags"]):BillSummary{return{billId:r.id,scope:r.scope,ownerUserId:r.owner_user_id,householdId:r.household_id,name:r.name,amount:normalizeDatabaseMoney(r.amount),currency:r.currency,walletId:r.wallet_id,walletName:r.wallet?.name??null,walletArchived:r.wallet?.is_archived??false,pocketId:r.pocket_id,pocketName:r.pocket?.name??null,pocketArchived:r.pocket?.is_archived??false,categoryId:r.category_id,categoryName:r.category?.name??null,categoryArchived:r.category?.archived_at!=null,title:r.title,note:r.note,recurrenceType:r.recurrence_type,intervalCount:r.interval_count,startDate:r.start_date,endDate:r.end_date,pausedAt:r.paused_at,archivedAt:r.archived_at,tags:t}}

export async function listBills(s:SupabaseClient<Database>,p:{scope:"PERSONAL"|"HOUSEHOLD";householdId?:string|null;includeArchived?:boolean}){let q=s.from("bills").select(BILL_SELECT).eq("scope",p.scope);if(p.scope==="HOUSEHOLD"&&p.householdId)q=q.eq("household_id",p.householdId);if(!p.includeArchived)q=q.is("archived_at",null);const {data,error}=await q.order("name");if(error){logDatabaseErrorInDev("listBills failed",error);return[]}const rows=(data??[]) as unknown as RawBill[];const tags=await tagsFor(s,rows.map(x=>x.id));return rows.map(x=>mapBill(x,tags.get(x.id)??[]))}
export async function getBill(s:SupabaseClient<Database>,id:string){const {data,error}=await s.from("bills").select(BILL_SELECT).eq("id",id).maybeSingle();if(error||!data){if(error)logDatabaseErrorInDev("getBill failed",error);return null}const r=data as unknown as RawBill;const tags=await tagsFor(s,[id]);return mapBill(r,tags.get(id)??[])}
export async function materializeBills(s:SupabaseClient<Database>,p:{scope:"PERSONAL"|"HOUSEHOLD";householdId?:string|null}){const {error}=await s.rpc("materialize_bill_occurrences",{p_scope:p.scope,p_household_id:p.householdId??null});if(error)logDatabaseErrorInDev("materializeBills failed",error)}

const OCC=`id,due_date,expected_amount,status,paid_transaction_id,paid_at,skipped_at,bill:bills(${BILL_SELECT}),paid_transaction:transactions(deleted_at,transaction_entries(amount))`;
type RawOcc={id:string;due_date:string;expected_amount:string|number;status:"OPEN"|"PAID"|"SKIPPED";paid_transaction_id:string|null;paid_at:string|null;skipped_at:string|null;bill:RawBill|null;paid_transaction:{deleted_at:string|null;transaction_entries:Array<{amount:string|number}>}|null};
function mapOcc(r:RawOcc,t:BillSummary["tags"]):BillOccurrenceSummary|null{if(!r.bill)return null;const b=mapBill(r.bill,t);const entry=r.paid_transaction?.transaction_entries[0];return{...b,occurrenceId:r.id,dueDate:r.due_date,expectedAmount:normalizeDatabaseMoney(r.expected_amount),status:r.status,displayStatus:billDisplayStatus(r.status,r.due_date),paidTransactionId:r.paid_transaction_id,paidAt:r.paid_at,skippedAt:r.skipped_at,paymentVoided:r.paid_transaction?.deleted_at!=null,actualAmount:entry?normalizeDatabaseMoney(entry.amount).replace(/^-/u,""):null}}
export async function listBillOccurrences(s:SupabaseClient<Database>,ids:string[],p?:{status?:"OPEN"|"PAID"|"SKIPPED";limit?:number}){if(!ids.length)return[];let q=s.from("bill_occurrences").select(OCC).in("bill_id",ids);if(p?.status)q=q.eq("status",p.status);q=q.order("due_date");if(p?.limit)q=q.limit(p.limit);const {data,error}=await q;if(error){logDatabaseErrorInDev("listBillOccurrences failed",error);return[]}const rows=(data??[]) as unknown as RawOcc[];const tags=await tagsFor(s,ids);return rows.map(r=>mapOcc(r,tags.get(r.bill?.id??"")??[])).filter((x):x is BillOccurrenceSummary=>x!==null)}
export async function getBillOccurrence(s:SupabaseClient<Database>,id:string){const {data,error}=await s.from("bill_occurrences").select(OCC).eq("id",id).maybeSingle();if(error||!data){if(error)logDatabaseErrorInDev("getBillOccurrence failed",error);return null}const r=data as unknown as RawOcc;if(!r.bill)return null;const tags=await tagsFor(s,[r.bill.id]);return mapOcc(r,tags.get(r.bill.id)??[])}

export async function createBill(s:SupabaseClient<Database>,p:Database["public"]["Tables"]["bills"]["Insert"]){const {data,error}=await s.from("bills").insert(p).select().single();if(error)throw error;return data}
export async function updateBill(s:SupabaseClient<Database>,id:string,p:Database["public"]["Tables"]["bills"]["Update"]){const {error}=await s.from("bills").update(p).eq("id",id);if(error)throw error}
export async function setBillTags(s:SupabaseClient<Database>,id:string,tags:string[]){const {error}=await s.rpc("set_bill_tags",{p_bill_id:id,p_tag_ids:tags});if(error)throw error}
export async function skipBill(s:SupabaseClient<Database>,id:string){const {error}=await s.rpc("skip_bill_occurrence",{p_occurrence_id:id});if(error)throw error}
export async function payBill(s:SupabaseClient<Database>,p:{occurrenceId:string;walletId:string;pocketId:string;categoryId:string;amount:string;title:string|null;note:string|null;occurredAt:string;tagIds:string[]}){const {data,error}=await s.rpc("pay_bill_occurrence",{p_occurrence_id:p.occurrenceId,p_wallet_id:p.walletId,p_pocket_id:p.pocketId,p_category_id:p.categoryId,p_amount:p.amount,p_title:p.title,p_note:p.note,p_occurred_at:p.occurredAt,p_tag_ids:p.tagIds});if(error)throw error;return data}
