"use client";
import { useActionState,useState } from "react";
import { Field,Input,Select,Textarea } from "@/components/ui/Field";
import { SubmitButton } from "@/components/ui/SubmitButton";
import type { HouseholdMemberWithProfile } from "@/features/household/types";
import { initialActionState } from "@/lib/types/action-state";
import { createCalendarEventAction,updateCalendarEventAction } from "../actions";
import { toBangkokInput } from "../domain/calendar";
import type { CalendarEventView } from "../types";

export function CalendarEventForm({members,event,variant="page"}:{members:HouseholdMemberWithProfile[];event?:CalendarEventView;/** Presentation only — no card chrome to strip either way; kept for API-consistency. */variant?:"page"|"sheet"}){void variant;const[state,action]=useActionState(event?updateCalendarEventAction:createCalendarEventAction,initialActionState);const[scope,setScope]=useState(event?.scope??"HOUSEHOLD");const[allDay,setAllDay]=useState(event?.is_all_day??false);const selected=new Set(event?.participants.map(p=>p.id));return <form action={action} className="flex flex-col gap-4">{event?<input type="hidden" name="eventId" value={event.id}/>:null}<Field label="ชื่อกิจกรรม" htmlFor="title"><Input id="title" name="title" required maxLength={120} defaultValue={event?.title}/></Field><Field label="ประเภท" htmlFor="scope">{event?<><Input id="scope" value={event.scope==="PERSONAL"?"ส่วนตัว":"ครอบครัว"} disabled/><input type="hidden" name="scope" value={event.scope}/></>:<Select id="scope" name="scope" value={scope} onChange={e=>setScope(e.target.value as typeof scope)}><option value="PERSONAL">ส่วนตัว</option><option value="HOUSEHOLD">ครอบครัว</option></Select>}</Field><label className="flex min-h-11 items-center gap-3"><input type="checkbox" name="isAllDay" checked={allDay} onChange={e=>setAllDay(e.target.checked)}/>ทั้งวัน</label>{allDay?<Field label="วันที่" htmlFor="allDayDate"><Input id="allDayDate" name="allDayDate" type="date" required defaultValue={event?.all_day_date??""}/></Field>:<><Field label="เริ่ม" htmlFor="startsLocal"><Input id="startsLocal" name="startsLocal" type="datetime-local" required defaultValue={toBangkokInput(event?.starts_at??null)}/></Field><Field label="สิ้นสุด" htmlFor="endsLocal"><Input id="endsLocal" name="endsLocal" type="datetime-local" defaultValue={toBangkokInput(event?.ends_at??null)}/></Field></>}{scope==="HOUSEHOLD"?<fieldset><legend className="mb-2 text-sm font-medium text-foreground-muted">ผู้เข้าร่วม</legend><div className="flex flex-col gap-2">{members.map(m=>{const name=m.profile?.display_name||m.profile?.email||"Member";return <label key={m.id} className="flex min-h-11 items-center gap-3 rounded-control border border-border px-3"><input type="checkbox" name="participantIds" value={m.id} defaultChecked={selected.has(m.id)}/>{name}</label>})}</div></fieldset>:null}<Field label="โน้ต" htmlFor="note"><Textarea id="note" name="note" maxLength={2000} defaultValue={event?.note??""}/></Field>{state.error?<p aria-live="polite" className="text-sm text-danger">{state.error}</p>:null}<SubmitButton size="lg">บันทึกกิจกรรม</SubmitButton></form>}
