import"server-only";import type{SupabaseClient}from"@supabase/supabase-js";import type{Database}from"@/types/database";import{normalizeDatabaseMoney}from"@/lib/utils/money";import{logDatabaseErrorInDev}from"@/lib/supabase/log-error";import type{CardInstallmentCandidate,CardInstallmentOccurrenceSummary,CardInstallmentPlanSummary,InstallmentOccurrenceSummary,InstallmentPlanSummary}from"./types";
export async function listInstallmentPlans(s:SupabaseClient<Database>,scope:"PERSONAL"|"HOUSEHOLD",householdId?:string|null){let q=s.from("installment_plans").select("*").eq("scope",scope);if(scope==="HOUSEHOLD"&&householdId)q=q.eq("household_id",householdId);const{data,error}=await q.order("created_at",{ascending:false});if(error){logDatabaseErrorInDev("listInstallmentPlans failed",error);return[]}return(data??[]).map(r=>({id:r.id,scope:r.scope,ownerUserId:r.owner_user_id,householdId:r.household_id,name:r.name,totalAmount:normalizeDatabaseMoney(r.total_amount),currency:r.currency,installmentCount:r.installment_count,startDate:r.start_date,intervalMonths:r.interval_months,walletId:r.wallet_id,pocketId:r.pocket_id,categoryId:r.category_id,title:r.title,note:r.note,archivedAt:r.archived_at}))}
export async function getInstallmentPlan(s:SupabaseClient<Database>,id:string):Promise<InstallmentPlanSummary|null>{const{data,error}=await s.from("installment_plans").select("*").eq("id",id).maybeSingle();if(error||!data)return null;return{id:data.id,scope:data.scope,ownerUserId:data.owner_user_id,householdId:data.household_id,name:data.name,totalAmount:normalizeDatabaseMoney(data.total_amount),currency:data.currency,installmentCount:data.installment_count,startDate:data.start_date,intervalMonths:data.interval_months,walletId:data.wallet_id,pocketId:data.pocket_id,categoryId:data.category_id,title:data.title,note:data.note,archivedAt:data.archived_at}}
export async function listInstallmentOccurrences(s:SupabaseClient<Database>,planId:string):Promise<InstallmentOccurrenceSummary[]>{const{data,error}=await s.from("installment_occurrences").select("*").eq("plan_id",planId).order("sequence_number");if(error)return[];return(data??[]).map(x=>({id:x.id,planId:x.plan_id,sequenceNumber:x.sequence_number,dueDate:x.due_date,expectedAmount:normalizeDatabaseMoney(x.expected_amount),status:x.status,paidTransactionId:x.paid_transaction_id,paidAt:x.paid_at}))}
export async function getInstallmentOccurrence(s:SupabaseClient<Database>,id:string){const{data}=await s.from("installment_occurrences").select("*").eq("id",id).maybeSingle();return data?{id:data.id,planId:data.plan_id,sequenceNumber:data.sequence_number,dueDate:data.due_date,expectedAmount:normalizeDatabaseMoney(data.expected_amount),status:data.status,paidTransactionId:data.paid_transaction_id,paidAt:data.paid_at} satisfies InstallmentOccurrenceSummary:null}
export async function listCardInstallmentPlans(s:SupabaseClient<Database>):Promise<CardInstallmentPlanSummary[]>{const{data,error}=await s.rpc("get_credit_card_installment_plans");if(error){logDatabaseErrorInDev("listCardInstallmentPlans failed",error);return[]}return(data??[]).map(r=>({planId:r.plan_id,cardAccountId:r.card_account_id,cardName:r.card_name,currency:r.currency,purchaseTransactionId:r.purchase_transaction_id,name:r.name,totalAmount:normalizeDatabaseMoney(r.total_amount),installmentCount:r.installment_count,firstDueDate:r.first_due_date,intervalMonths:r.interval_months,paidCount:Number(r.paid_count),nextDueDate:r.next_due_date,nextDueAmount:r.next_due_amount===null?null:normalizeDatabaseMoney(r.next_due_amount),archivedAt:r.archived_at}))}
export async function getCardInstallmentPlan(s:SupabaseClient<Database>,id:string){return(await listCardInstallmentPlans(s)).find(p=>p.planId===id)??null}
export async function listCardInstallmentOccurrences(s:SupabaseClient<Database>,planId:string):Promise<CardInstallmentOccurrenceSummary[]>{const{data,error}=await s.rpc("get_credit_card_installment_occurrences",{p_plan_id:planId});if(error){logDatabaseErrorInDev("listCardInstallmentOccurrences failed",error);return[]}return(data??[]).map(r=>({occurrenceId:r.occurrence_id,sequenceNumber:r.sequence_number,dueDate:r.due_date,expectedAmount:normalizeDatabaseMoney(r.expected_amount),status:r.status as CardInstallmentOccurrenceSummary["status"],paymentTransactionId:r.payment_transaction_id,paidAt:r.paid_at}))}
export async function getCardInstallmentOccurrence(s:SupabaseClient<Database>,planId:string,occurrenceId:string){return(await listCardInstallmentOccurrences(s,planId)).find(o=>o.occurrenceId===occurrenceId)??null}
export async function listCardInstallmentCandidates(s:SupabaseClient<Database>,cardAccountId:string):Promise<CardInstallmentCandidate[]>{const{data,error}=await s.rpc("get_credit_card_installment_candidates",{p_card_account_id:cardAccountId});if(error){logDatabaseErrorInDev("listCardInstallmentCandidates failed",error);return[]}return(data??[]).map(r=>({transactionId:r.transaction_id,title:r.title,occurredAt:r.occurred_at,amount:normalizeDatabaseMoney(r.amount)}))}
