"use client";

import { useActionState, useState } from "react";
import { Field, Input, Select } from "@/components/ui/Field";
import { SubmitButton } from "@/components/ui/SubmitButton";
import type { Wallet } from "@/features/wallets/types";
import type { Pocket } from "@/features/pockets/types";
import type { CategoryNode } from "@/features/categories/types";
import { initialActionState } from "@/lib/types/action-state";
import { createDebtAction, recordAdditionalDebtPrincipalAction, recordDebtPaymentAction } from "../actions";

type CashProps={debtId:string;wallets:Wallet[];pockets:Record<string,Pocket[]>};
function CashFields({wallets,pockets,w,setW}:{wallets:Wallet[];pockets:Record<string,Pocket[]>;w:string;setW:(id:string)=>void}){return <><Field label="Wallet" htmlFor="walletId"><Select id="walletId" name="walletId" value={w} onChange={e=>setW(e.target.value)}>{wallets.map(x=><option key={x.id} value={x.id}>{x.name} · {x.currency}</option>)}</Select></Field><Field label="Pocket" htmlFor="pocketId"><Select id="pocketId" name="pocketId">{(pockets[w]??[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field></>}
export function DebtCreateForm({wallets,pockets,hasHousehold}:{wallets:Wallet[];pockets:Record<string,Pocket[]>;hasHousehold:boolean}){const[state,a]=useActionState(createDebtAction,initialActionState);const[w,setW]=useState(wallets[0]?.id??"");return <form action={a} className="flex flex-col gap-3"><Field label="ขอบเขต" htmlFor="scope"><Select id="scope" name="scope"><option value="PERSONAL">ส่วนตัว</option>{hasHousehold?<option value="HOUSEHOLD">ครอบครัว</option>:null}</Select></Field><Field label="ประเภท" htmlFor="debtType"><Select id="debtType" name="debtType"><option value="LIABILITY">เงินที่เรายืม</option><option value="RECEIVABLE">เงินที่เราให้ยืม</option></Select></Field><Field label="ชื่อ" htmlFor="name"><Input id="name" name="name" required/></Field><Field label="คู่สัญญา" htmlFor="counterparty"><Input id="counterparty" name="counterparty"/></Field><Field label="เงินต้น" htmlFor="principal"><Input id="principal" name="principal" required/></Field><Field label="สกุลเงิน" htmlFor="currency"><Input id="currency" name="currency" defaultValue="THB" required/></Field><CashFields wallets={wallets} pockets={pockets} w={w} setW={setW}/>{state.error?<p className="text-danger">{state.error}</p>:null}<SubmitButton>บันทึก</SubmitButton></form>}
export function DebtPaymentForm({debtId,wallets,pockets,categories}:CashProps&{categories:CategoryNode[]}){const[state,a]=useActionState(recordDebtPaymentAction,initialActionState);const[w,setW]=useState(wallets[0]?.id??"");const cats=categories.flatMap(x=>[x,...x.children]);return <form action={a} className="flex flex-col gap-3"><input type="hidden" name="debtId" value={debtId}/><Field label="เงินต้น" htmlFor="principal"><Input id="principal" name="principal" required/></Field><Field label="ดอกเบี้ย/ค่าธรรมเนียม" htmlFor="interest"><Input id="interest" name="interest" defaultValue="0.00" required/></Field><CashFields wallets={wallets} pockets={pockets} w={w} setW={setW}/><Field label="หมวดดอกเบี้ย" htmlFor="categoryId"><Select id="categoryId" name="categoryId">{cats.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field>{state.error?<p className="text-danger">{state.error}</p>:null}<SubmitButton>บันทึกการชำระ</SubmitButton></form>}
export function AdditionalDebtPrincipalForm({debtId,wallets,pockets}:CashProps){const[state,a]=useActionState(recordAdditionalDebtPrincipalAction,initialActionState);const[w,setW]=useState(wallets[0]?.id??"");return <form action={a} className="flex flex-col gap-3"><input type="hidden" name="debtId" value={debtId}/><Field label="เงินต้นเพิ่ม" htmlFor="principal"><Input id="principal" name="principal" required/></Field><CashFields wallets={wallets} pockets={pockets} w={w} setW={setW}/>{state.error?<p className="text-danger">{state.error}</p>:null}<SubmitButton>บันทึกเงินต้นเพิ่ม</SubmitButton></form>}
